version: '3.9'
services:
  api:
    image: yngvemag/ga-friidrett-api:latest
    depends_on:
      - db
    restart: always
    container_name: api
   
  db:
    image: yngvemag/ga-friidrett-db:latest
    volumes:
      - dbvol-gafriidrett-spring:/var/lib/mysql
    restart: always
    container_name: db
     
  server:
    image: yngvemag/ga-friidrett-server:latest
    ports:
      - 80:81
    depends_on:
      - api
    restart: always
    container_name: server

volumes:
  dbvol-gafriidrett-spring:
